[package]
name = "join-proxy"
version = "0.0.1"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-web = { version = "4.11.0", features = ["macros", "http2", "rustls-0_23"] }
anyhow = "1.0.100"
bytes = "1.10.1"
clap = { version = "4.5.49", features = ["derive"] }
derive_more = "2.0.1"
http = "1.3.1"
http_for_actix = { version = "0.2.12", package = "http" }
log = "0.4.28"
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.145"
sha2 = "0.10.9"
thiserror = "2.0.17"
ic-agent = "0.44.2"
base64 = "0.22.1"
tokio = { version = "1.48.0", features = ["macros"] }
async-trait = "0.1.89"
candid = { version = "0.10.20", features = ["value"] }
toml = "0.9.8"
rustls = "0.23.32"
rustls-pemfile = "2.2.0"
env_logger = "0.11.8"
diesel = { version = "2.3.2", features = ["postgres", "postgres_backend", "chrono", "uuid", "r2d2", "32-column-tables"] }
reqwest = { version = "0.12.24", features = ["http2", "default-tls", "charset", "cookies", "gzip", "brotli", "zstd", "deflate", "json", "multipart", "stream", "system-proxy"] }
hex = "0.4.3"
oxide-auth-actix = "0.3.0"
oxide-auth = "0.6.1"
url = "2.5.7"
serde_urlencoded = "0.7.1"
merge = { git = "https://git.sr.ht/~porton/merge-rs", version = "0.2.0", branch = "feat/overwrite_by_some" }
merge_derive = { git = "https://git.sr.ht/~porton/merge-rs", version = "0.2.0", branch = "feat/overwrite_by_some" }
rand = "0.8.5"
der = "0.7.9"
pkcs8 = "0.10.2"
sec1 = "0.7.3"
k256 = { version = "0.13.4", features = ["ecdsa"] }
p256 = { version = "0.13.2", features = ["ecdsa"] }
elliptic-curve = "0.13.8"
ic-ed25519 = "0.2.0"
chrono = { version = "0.4.38", features = ["serde"] }
actix-cors = "0.7.1"
blsttc = "8.0.2"
subtle = "2.6.1"
# lock_api = "0.4.12"
# future-parking_lot = "0.3.3"
